#!/bin/bash
scripts_path="${HOME}/.local/scripts"

if [[ -d "$scripts_path" ]]
then
	choice=$(ls "$scripts_path" | rofi -theme cute -dmenu -l 5)
	"${scripts_path}/${choice}" | ${SHELL:-"/bin/sh"} &
else
	rofi -e "Scripts directory doesn't exists!"
fi
